services:
  frontend:
    build:
      context: .
    restart: unless-stopped
    ports:
      - ${INTERNAL_PORT}:80

  cloudflare:
    image: cloudflare/cloudflared:latest
    command: tunnel --no-autoupdate run
    restart: unless-stopped
    environment:
      - ${CLOUDFLARE_}=${CLOUDFLARE}
